name: flutter_mongo_stitch_platform_interface
description: A new Flutter package project.
version: 1.2.2
homepage: https://github.com/kfiross/flutter_mongo_stitch_platform_interface

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
